[Settings]
Priority=Default

[Default]
OSInstall=Y
SkipCapture=YES
SkipProductKey=YES

; SkipComputerName=YES
OSDComputerName=WIN-#Right("%UUID%",8)#

; SkipDomainMembership=YES
JoinWorkgroup=WORKGROUP

; SkipUserData=Yes
UserDataLocation=NONE

; SkipComputerBackup=YES
ComputerBackupLocation=NONE

; SkipLocaleSelection=YES  
UILanguage=en-US  
UserLocale=uk-ua  
KeyboardLocale=0409:00000409  

; SkipTimeZone=YES  
TimeZoneName=FLE Standard Time

; SkipAdminPassword=YES
AdminPassword=password
; SkipBitLocker=YES

BDEInstall=NO
BDEInstallSuppress=YES
; SkipSummary=YES
